on:
  push:
    branches:
      - route53
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2

    #   - name: Setup Node
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: "14"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

        # Build App and Run Application Test
      - name: Run unit Test
        # run: node index.js
        run: python dns.py
        
      - name: Git auto commit actions  
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
          commit_message: Automated Change
